spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

#server.port=${SERVER_PORT}

server.port=${PORT:8080}

app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS}

razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}
razorpay.currency=${RAZORPAY_CURRENCY}

frontend.url=${FRONTEND_URL}
